# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_product_compare_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_compare:indexAction

